apiVersion: batch/v1
kind: Job
metadata:
  name: chang-luau
spec:
  template:
    spec: 
      containers:
      - name: chang-luau
        image: gitlab-registry.nrp-nautilus.io/oliverc1622/luau:latest
        securityContext:
          runAsUser: 0
        command: ["/bin/bash", "-c"]
        args: 
          - |
            cd ~ && \
            git clone https://github.com/oliverc1623/luau.git && cd luau && \
            chmod +x nautilus/run_experiment.sh && ./nautilus/run_experiment.sh
        volumeMounts: 
        - mountPath: /pvcvolume
          name: elochang-rbd-volume
        - mountPath: /dev/shm
          name: dshm
        resources: 
          limits:
            memory: 32Gi
            cpu: "16"
            nvidia.com/gpu: "1"
          requests: 
            memory: 16Gi
            cpu: "8"
            nvidia.com/gpu: "1"
      volumes: 
        - name: elochang-rbd-volume
          persistentVolumeClaim: 
            claimName: elochang-rbd-volume
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-A10
      restartPolicy: Never
  backoffLimit: 3 
