apiVersion: v1
kind: Pod
metadata:
  name: chang-luau
spec:
  containers:
  - name: chang-hippo
    image: gitlab-registry.nrp-nautilus.io/oliverc1622/luau:latest
    securityContext:
        runAsUser: 0
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts: 
    - mountPath: /pvcvolume
      name: elochang-volume2
    - mountPath: /dev/shm
      name: dshm
    resources: 
      limits:
        memory: 32Gi
        cpu: "16"
        nvidia.com/gpu: "1"
      requests: 
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-token
          key: token
  volumes: 
    - name: elochang-volume2
      persistentVolumeClaim: 
        claimName: elochang-volume2
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
              - NVIDIA-GeForce-RTX-3090
